using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using SWIBLL;

namespace DXSWI.Modules
{
    public partial class frCandidates : DevExpress.XtraEditors.XtraUserControl
    {
        CandidateManager mCandidateManager = new CandidateManager();
        public frCandidates()
        {
            InitializeComponent();
            init();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
        }

        private void init()
        {
            // load data in candidate table and show in grid control
            gcCandidates.DataSource = mCandidateManager.getCurrentPages();
            gcCandidates.DataMember = "candidate";
            //gcCandidates.DataSource = mCandidateManager.getCurrentPages();
        }

        private void gcCandidates_Click(object sender, EventArgs e)
        {

        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (e.FocusedRowHandle == DevExpress.XtraGrid.GridControl.AutoFilterRowHandle)
                gridView1.FocusedColumn = colFirstName;
            else if (e.FocusedRowHandle >= 0)
                gridView1.FocusedColumn = null;
            updateCurrentCandidate();
        }

        private void gridView1_ColumnFilterChanged(object sender, EventArgs e)
        {

        }
        void updateCurrentCandidate()
        {
            //frCandidates.
            if (gcCandidates.MainView == gridView1)
                gridView1.MakeRowVisible(gridView1.FocusedRowHandle);
            //OwnerForm.EnableEditContact(CurrentContact != null); // enable edit button
        }



        //Contact CurrentContact
        //{
        //    get { return ((ColumnView)gridControl1.MainView).GetFocusedRow() as Contact; }
        //}
    }
}

