using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.ComponentModel.DataAnnotations;

namespace DXSWI.Modules
{
    public partial class frUser : DevExpress.XtraEditors.XtraUserControl
    {
        public frUser()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //try {
            //    sqlDataSource1.Fill();
            //} catch(Exception ex)
            //{
            //    MessageBox.Show(ex.Message);
            //}
        }
        void windowsUIButtonPanel_ButtonClick(object sender, DevExpress.XtraBars.Docking2010.ButtonEventArgs e)
        {
            if (e.Button.Properties.Caption == "Print") gridControl.ShowRibbonPrintPreview();
        }
    }
}
